### ISSUE TITLE
Add support for HSET, HMSET etc.

### ISSUE THREAD

**Issue by Jannis** [onyx-platform/onyx-redis#7]
A lot of the commands supported by carmine are currently not supported by onyx-redis. It would be nice to have a more complete coverage of the Redis API.

**Comment by gardnervickers** [comment]
@jcf brought up using https://github.com/ptaoussanis/carmine/blob/master/src/taoensso/carmine/commands.clj#L144-L154 to generate our list of commands in a static map for lookup perf.
